/*
 * JFrameCC.java
 *
 * Created on 3 maj 2007, 20:20
 */

package cc;

import java.awt.*;
import javax.media.*;
import javax.swing.*;
import java.awt.event.*;

/**
 *
 * @author  Damian Hintz
 */
public class JFrameCC extends javax.swing.JFrame 
{
    
    private CameraClient cc;
    private String address;
    private int port;
    
    private Component visualComponent;
    private Component controlComponent;
    
    /** Creates new form JFrameCC */
    public JFrameCC() {
        setTitle("cc - camera client");
        initComponents();
    }
    
    public void addPlayer(Player player)
    {
        
        visualComponent = player.getVisualComponent();
        controlComponent = player.getControlPanelComponent();

        //this.jPanelVC.setLayout(null);
        
        this.jPanelCC.add(controlComponent);
        this.jPanelVC.add(visualComponent);
        
        int width = visualComponent.getPreferredSize().width;
        int height = visualComponent.getPreferredSize().height;
        
        //this.jPanelVC.setBounds(jPanelVC.getX(), jPanelVC.getY(), width, height);
        //this.jPanelVC.setSize(vc.getPreferredSize());
        this.jPanelCC.setBounds(jPanelCC.getX(), jPanelCC.getY(), width, controlComponent.getPreferredSize().height);
        
        controlComponent.invalidate();
        controlComponent.validate();
        visualComponent.validate();
        jPanelCC.validate();
        jPanelVC.validate();
        
        visualComponent.setSize(jPanelVC.getSize());
        controlComponent.setSize(jPanelCC.getSize());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jToolBar1 = new javax.swing.JToolBar();
        jLabelAddress = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jLabelPort = new javax.swing.JLabel();
        jTextFieldPort = new javax.swing.JTextField();
        jButtonServer = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        jLabelCamera = new javax.swing.JLabel();
        jComboBoxCamera = new javax.swing.JComboBox();
        jButtonCamera = new javax.swing.JButton();
        jPanelVC = new javax.swing.JPanel();
        jPanelCC = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jToolBar1.setFloatable(false);
        jLabelAddress.setText("Address: ");
        jToolBar1.add(jLabelAddress);

        jTextFieldAddress.setText("192.168.3.1");
        jToolBar1.add(jTextFieldAddress);

        jLabelPort.setText(" Port: ");
        jToolBar1.add(jLabelPort);

        jTextFieldPort.setText("4321");
        jToolBar1.add(jTextFieldPort);

        jButtonServer.setText("Connect to server");
        jButtonServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonServerActionPerformed(evt);
            }
        });

        jToolBar1.add(jButtonServer);

        jToolBar2.setFloatable(false);
        jLabelCamera.setText("Camera: ");
        jToolBar2.add(jLabelCamera);

        jToolBar2.add(jComboBoxCamera);

        jButtonCamera.setText("Connect to camera");
        jButtonCamera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCameraActionPerformed(evt);
            }
        });

        jToolBar2.add(jButtonCamera);

        jPanelVC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelVC.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jPanelVCComponentResized(evt);
            }
        });

        javax.swing.GroupLayout jPanelVCLayout = new javax.swing.GroupLayout(jPanelVC);
        jPanelVC.setLayout(jPanelVCLayout);
        jPanelVCLayout.setHorizontalGroup(
            jPanelVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 331, Short.MAX_VALUE)
        );
        jPanelVCLayout.setVerticalGroup(
            jPanelVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 241, Short.MAX_VALUE)
        );

        jPanelCC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        javax.swing.GroupLayout jPanelCCLayout = new javax.swing.GroupLayout(jPanelCC);
        jPanelCC.setLayout(jPanelCCLayout);
        jPanelCCLayout.setHorizontalGroup(
            jPanelCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 331, Short.MAX_VALUE)
        );
        jPanelCCLayout.setVerticalGroup(
            jPanelCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
            .addComponent(jPanelCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelVC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelVC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelVCComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanelVCComponentResized
        if(visualComponent != null)
        {
            visualComponent.setSize(jPanelVC.getSize());
        }
    }//GEN-LAST:event_jPanelVCComponentResized

    private void jButtonCameraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCameraActionPerformed
        int cameraIndex = (Integer)jComboBoxCamera.getSelectedItem();
        this.setTitle("CC connecting camera " + cameraIndex + "...");
        cc.connectToCamera(cameraIndex);
        this.setTitle("CC camera " + cameraIndex + " connected");
    }//GEN-LAST:event_jButtonCameraActionPerformed

    public void removePlayer()
    {
        setTitle("cc disconnected");
        jButtonServer.setText("Connect to server");
        jComboBoxCamera.removeAllItems();
        this.jPanelCC.removeAll();
        this.jPanelVC.removeAll();
    }
    
    private void jButtonServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonServerActionPerformed
        if(jButtonServer.getText().startsWith("Connect"))
        {
            if(connectToServer())
            {
                jButtonServer.setText("Disconnect from server");
            }
        }else
        {
            disconnectFromServer();
            jButtonServer.setText("Connect to server");
        }
    }//GEN-LAST:event_jButtonServerActionPerformed

    private boolean connectToServer()
    {
        this.setTitle("CC connecting...");
        
        jComboBoxCamera.removeAllItems();
        
        address = jTextFieldAddress.getText();
        try
        {
            port = Integer.parseInt(jTextFieldPort.getText());
        }catch(NumberFormatException e)
        {
            port = 0;
        }
        
        if(port < 1024)
        {
            this.setTitle("CC port error (<=1024)");
            return false;
        }
        
        cc = new CameraClient(address, port, this);
        
        if(cc.getEnabled() == false)
        {
            this.setTitle("CC connection error");
            return false;
        }

        int cameras = cc.countCameras();
        for(int i = 0; i < cameras;i++)
        {
            jComboBoxCamera.addItem(i);
        }

        this.setTitle("CC connected");
            
        return true;    
    }
        
    private void disconnectFromServer()
    {
        this.setTitle("CC disconnecting...");
        jComboBoxCamera.removeAllItems();
        cc.disconnectFromServer();
        this.setTitle("CC disconnected");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCC().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCamera;
    private javax.swing.JButton jButtonServer;
    private javax.swing.JComboBox jComboBoxCamera;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelCamera;
    private javax.swing.JLabel jLabelPort;
    private javax.swing.JPanel jPanelCC;
    private javax.swing.JPanel jPanelVC;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldPort;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
    
}
